name: "Setup Chisel"
description: "Download, verify, and install Canonical Chisel"
author: "Mattheish"
branding:
  icon: "download"
  color: "blue"

inputs:
  version:
    description: "Chisel release version (e.g. v1.3.0 or 'latest')"
    required: true
    default: "v1.3.0"
  install-wrapper:
    description: "Whether to install the chisel-wrapper script"
    required: false
    default: "false"

outputs:
  version:
    description: "Installed Chisel version"
    value: ${{ steps.resolve-version.outputs.version }}
  architecture:
    description: "Detected architecture"
    value: ${{ steps.detect-arch.outputs.architecture }}

runs:
  using: "composite"
  steps:
    - name: Resolve Chisel version
      id: resolve-version
      shell: bash
      run: |
        set -euo pipefail

        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = "latest" ]; then
          VERSION=$(curl -fsSL https://api.github.com/repos/canonical/chisel/releases/latest | jq -r '.tag_name')
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Detect runner architecture
      id: detect-arch
      shell: bash
      run: |
        set -euo pipefail

        ARCH=$(uname -m)
        case "$ARCH" in
          x86_64)   ARCH="amd64"   ;;
          aarch64)  ARCH="arm64"   ;;
          armv7l)   ARCH="arm"     ;;
          ppc64le)  ARCH="ppc64le" ;;
          riscv64)  ARCH="riscv64" ;;
          s390x)    ARCH="s390x"   ;;
          *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
        esac

        echo "architecture=$ARCH" >> $GITHUB_OUTPUT

    - name: Download and verify Chisel
      id: download
      shell: bash
      run: |
        set -euo pipefail

        VERSION="${{ steps.resolve-version.outputs.version }}"
        ARCH="${{ steps.detect-arch.outputs.architecture }}"
        ASSET="chisel_${VERSION}_linux_${ARCH}.tar.gz"
        BASE_URL="https://github.com/canonical/chisel/releases/download/${VERSION}"

        echo "Downloading from ${BASE_URL}/${ASSET}"
        curl -fsSL -o "${ASSET}" "${BASE_URL}/${ASSET}"
        curl -fsSL -o "${ASSET}.sha384" "${BASE_URL}/${ASSET}.sha384"

        echo "Verifying checksum..."
        sha384sum -c "${ASSET}.sha384"
        
        echo "asset=${ASSET}" >> $GITHUB_OUTPUT

    - name: Extract and install Chisel
      shell: bash
      run: |
        set -euo pipefail

        ASSET="${{ steps.download.outputs.asset }}"

        echo "Extracting ${ASSET}"
        tar -xzf "${ASSET}"

        chmod +x chisel

        echo "Adding chisel to the path"
        echo "$PWD" >> $GITHUB_PATH

    - name: Download and install chisel-wrapper
      if: ${{ inputs.install-wrapper == 'true' }}
      shell: bash
      run: |
        set -euo pipefail

        WRAPPER_URL="https://raw.githubusercontent.com/canonical/rocks-toolbox/main/chisel-wrapper"
        echo "Downloading chisel-wrapper from ${WRAPPER_URL}"
        curl -fsSL -o chisel-wrapper "$WRAPPER_URL"
        chmod +x chisel-wrapper